### ISSUE TITLE
Validate indexer address input configuration to ensure its parsed as a string and not a number

### ISSUE THREAD

**Issue by chriswessels** [graphops/subgraph-radio#80] opened 2023-09-18 14:11 UTC

**Comment by hopeyen** [comment] 2023-09-18 14:28
Resolve by https://github.com/graphops/subgraph-radio/issues/78

**Comment by cargopete** [comment] 2023-09-29 11:45
closing as duplicate of https://github.com/graphops/subgraph-radio/issues/78

**Closed as not planned by cargopete** 2023-09-29 11:45 UTC
Labels: type:bug, size:small, p1, meta:triaged
